name: "Static Site Screenshot"
description: "Captures screenshots of web pages using Playwright and saves them as image files."
author: "Krishna Kumar"
inputs:
  screenshots:
    description: "Comma-separated list of URL paths and output file paths in format '/=screenshot.webp,topics/=topics/screenshot.webp,chat.html=img/chat.png'"
    required: true
    default: "/=screenshot.webp"

  width:
    description: "Viewport width in pixels for the screenshot"
    required: false
    default: "1280"
  height:
    description: "Viewport height in pixels. If specified, captures only this height; otherwise captures full page"
    required: false
  webp_options:
    description: "JSON string with WebP format options"
    required: false
    default: "{\"lossless\":true,\"quality\":100,\"effort\":6}"
  png_options:
    description: "JSON string with PNG format options"
    required: false
    default: "{\"quality\":100}"
  jpeg_options:
    description: "JSON string with JPEG format options"
    required: false
    default: "{\"quality\":90}"
runs:
  using: "composite"
  steps:
    - name: Install dependencies and run screenshot
      shell: bash
      run: |
        cd ${{ github.action_path }}
        npm install playwright sharp polka sirv pino
        npx playwright install --with-deps chromium
        node ${{ github.action_path }}/screenshot.js
      env:
        SCREENSHOTS: ${{ inputs.screenshots }}
        INPUT_WIDTH: ${{ inputs.width }}
        INPUT_HEIGHT: ${{ inputs.height }}
        INPUT_WEBP_OPTIONS: ${{ inputs.webp_options }}
        INPUT_PNG_OPTIONS: ${{ inputs.png_options }}
        INPUT_JPEG_OPTIONS: ${{ inputs.jpeg_options }}
        INPUT_PORT: "3000"