name: "Static Site Screenshot"
description: "Launches a local server and captures a full-page WebP screenshot of the page using Playwright."
author: "Krishna Kumar"
inputs:
  url:
    description: "The URL to screenshot (e.g. http://localhost:5000)"
    required: true
  output:
    description: "Output file path (e.g. screenshot.webp)"
    required: false
    default: "screenshot.webp"
runs:
  using: "composite"
  steps:
    - name: Run screenshot script
      shell: bash
      run: node ${{ github.action_path }}/screenshot.js
      env:
        INPUT_URL: ${{ inputs.url }}
        INPUT_OUTPUT: ${{ inputs.output }}